/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import personalInformation.Adress;
import personalInformation.CheckingAccount;
import personalInformation.DemographicInformation;
import personalInformation.License;
import personalInformation.MedicalInfo;
import personalInformation.SavingAccount;

/**
 *
 * @author admin
 */
public class viewReport extends javax.swing.JPanel {

      SavingAccount savingAccount;
      DemographicInformation demographicInformation ;
    CheckingAccount checkingAccount;
    
    Adress adress;
    License license;
    MedicalInfo medicalInfo;
    
    /**
     * Creates new form viewDemographicInformation
     */
    public viewReport(DemographicInformation demoinfo,CheckingAccount checkingAccount,SavingAccount savingAccount,Adress adress,License license,MedicalInfo medicalInfo) {
        initComponents();
        this.savingAccount=savingAccount;
        this.demographicInformation= demoinfo ;
    this.checkingAccount=checkingAccount;
    
    this.adress=adress;
    this.medicalInfo=medicalInfo;
    this.license=license;
    
    
    
    displayReport();
        
    
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblState1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblState2 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblState3 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblState4 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblState5 = new javax.swing.JLabel();
        lblState6 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtRNS = new javax.swing.JTextField();
        lblState7 = new javax.swing.JLabel();
        txtBNS = new javax.swing.JTextField();
        lblState8 = new javax.swing.JLabel();
        txtBANS = new javax.swing.JTextField();
        lblState10 = new javax.swing.JLabel();
        txtBankName11 = new javax.swing.JTextField();
        lblState11 = new javax.swing.JLabel();
        txtABS = new javax.swing.JTextField();
        lblState12 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblState19 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblState20 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        lblState23 = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        lblState24 = new javax.swing.JLabel();
        txtDoe = new javax.swing.JTextField();
        lblState25 = new javax.swing.JLabel();
        txtDoi = new javax.swing.JTextField();
        lblState26 = new javax.swing.JLabel();
        txtLN = new javax.swing.JTextField();
        lblState29 = new javax.swing.JLabel();
        txtBt = new javax.swing.JTextField();
        lblState30 = new javax.swing.JLabel();
        txta2 = new javax.swing.JTextField();
        lblState31 = new javax.swing.JLabel();
        txta1 = new javax.swing.JTextField();
        lblState32 = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        lblState35 = new javax.swing.JLabel();
        txta3 = new javax.swing.JTextField();
        lblState36 = new javax.swing.JLabel();
        lblState9 = new javax.swing.JLabel();
        txtBNC = new javax.swing.JTextField();
        lblState13 = new javax.swing.JLabel();
        txtRNC = new javax.swing.JTextField();
        lblState14 = new javax.swing.JLabel();
        txtABC = new javax.swing.JTextField();
        lblState15 = new javax.swing.JLabel();
        txtAccountType = new javax.swing.JTextField();
        lblState16 = new javax.swing.JLabel();
        txtBANC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblState17 = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        lblReportImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(536, 484));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORT ");

        txtFirstName.setEditable(false);
        txtFirstName.setForeground(new java.awt.Color(51, 51, 51));
        txtFirstName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblState1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState1.setForeground(new java.awt.Color(102, 102, 102));
        lblState1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState1.setText("First Name");
        lblState1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtLastName.setEditable(false);
        txtLastName.setForeground(new java.awt.Color(51, 51, 51));
        txtLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblState2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState2.setForeground(new java.awt.Color(102, 102, 102));
        lblState2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState2.setText("Last Name");
        lblState2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtHeight.setEditable(false);
        txtHeight.setForeground(new java.awt.Color(51, 51, 51));
        txtHeight.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        lblState3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState3.setForeground(new java.awt.Color(102, 102, 102));
        lblState3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState3.setText("Height");
        lblState3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtWeight.setEditable(false);
        txtWeight.setForeground(new java.awt.Color(51, 51, 51));
        txtWeight.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        lblState4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState4.setForeground(new java.awt.Color(102, 102, 102));
        lblState4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState4.setText("Weight");
        lblState4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtAge.setEditable(false);
        txtAge.setForeground(new java.awt.Color(51, 51, 51));
        txtAge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblState5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState5.setForeground(new java.awt.Color(102, 102, 102));
        lblState5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState5.setText("Age");
        lblState5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblState6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState6.setForeground(new java.awt.Color(102, 102, 102));
        lblState6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState6.setText("Social Security Number");
        lblState6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtSSN.setEditable(false);
        txtSSN.setForeground(new java.awt.Color(51, 51, 51));
        txtSSN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        txtRNS.setEditable(false);
        txtRNS.setForeground(new java.awt.Color(51, 51, 51));
        txtRNS.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtRNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRNSActionPerformed(evt);
            }
        });

        lblState7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState7.setForeground(new java.awt.Color(102, 102, 102));
        lblState7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState7.setText("Bank Name");
        lblState7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtBNS.setEditable(false);
        txtBNS.setForeground(new java.awt.Color(51, 51, 51));
        txtBNS.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtBNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBNSActionPerformed(evt);
            }
        });

        lblState8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState8.setForeground(new java.awt.Color(102, 102, 102));
        lblState8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState8.setText("Bank Account Number");
        lblState8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtBANS.setEditable(false);
        txtBANS.setForeground(new java.awt.Color(51, 51, 51));
        txtBANS.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtBANS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBANSActionPerformed(evt);
            }
        });

        lblState10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState10.setForeground(new java.awt.Color(102, 102, 102));
        lblState10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState10.setText("Account Type");
        lblState10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtBankName11.setEditable(false);
        txtBankName11.setForeground(new java.awt.Color(51, 51, 51));
        txtBankName11.setText("Saving");
        txtBankName11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtBankName11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankName11ActionPerformed(evt);
            }
        });

        lblState11.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState11.setForeground(new java.awt.Color(102, 102, 102));
        lblState11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState11.setText("Account Balance");
        lblState11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtABS.setEditable(false);
        txtABS.setForeground(new java.awt.Color(51, 51, 51));
        txtABS.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtABS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtABSActionPerformed(evt);
            }
        });

        lblState12.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState12.setForeground(new java.awt.Color(102, 102, 102));
        lblState12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState12.setText("Routing Number");
        lblState12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtState.setEditable(false);
        txtState.setForeground(new java.awt.Color(51, 51, 51));
        txtState.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        lblState19.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState19.setForeground(new java.awt.Color(102, 102, 102));
        lblState19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState19.setText("City");
        lblState19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtCity.setEditable(false);
        txtCity.setForeground(new java.awt.Color(51, 51, 51));
        txtCity.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblState20.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState20.setForeground(new java.awt.Color(102, 102, 102));
        lblState20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState20.setText("Street Address");
        lblState20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtStreet.setEditable(false);
        txtStreet.setForeground(new java.awt.Color(51, 51, 51));
        txtStreet.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });

        lblState23.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState23.setForeground(new java.awt.Color(102, 102, 102));
        lblState23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState23.setText("Zipcode");
        lblState23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtZipcode.setEditable(false);
        txtZipcode.setForeground(new java.awt.Color(51, 51, 51));
        txtZipcode.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipcodeActionPerformed(evt);
            }
        });

        lblState24.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState24.setForeground(new java.awt.Color(102, 102, 102));
        lblState24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState24.setText("State");
        lblState24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtDoe.setEditable(false);
        txtDoe.setForeground(new java.awt.Color(51, 51, 51));
        txtDoe.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtDoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoeActionPerformed(evt);
            }
        });

        lblState25.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState25.setForeground(new java.awt.Color(102, 102, 102));
        lblState25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState25.setText("Date of Issue");
        lblState25.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtDoi.setEditable(false);
        txtDoi.setForeground(new java.awt.Color(51, 51, 51));
        txtDoi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoiActionPerformed(evt);
            }
        });

        lblState26.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState26.setForeground(new java.awt.Color(102, 102, 102));
        lblState26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState26.setText("License Number");
        lblState26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtLN.setEditable(false);
        txtLN.setForeground(new java.awt.Color(51, 51, 51));
        txtLN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNActionPerformed(evt);
            }
        });

        lblState29.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState29.setForeground(new java.awt.Color(102, 102, 102));
        lblState29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState29.setText("Blood Type");
        lblState29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtBt.setEditable(false);
        txtBt.setForeground(new java.awt.Color(51, 51, 51));
        txtBt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBtActionPerformed(evt);
            }
        });

        lblState30.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState30.setForeground(new java.awt.Color(102, 102, 102));
        lblState30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState30.setText("Date of Expiration");
        lblState30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblState30.setAlignmentX(0.2F);

        txta2.setEditable(false);
        txta2.setForeground(new java.awt.Color(51, 51, 51));
        txta2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txta2ActionPerformed(evt);
            }
        });

        lblState31.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState31.setForeground(new java.awt.Color(102, 102, 102));
        lblState31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState31.setText("Allergy 1");
        lblState31.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txta1.setEditable(false);
        txta1.setForeground(new java.awt.Color(51, 51, 51));
        txta1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txta1ActionPerformed(evt);
            }
        });

        lblState32.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState32.setForeground(new java.awt.Color(102, 102, 102));
        lblState32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState32.setText("Medical Record Numer");
        lblState32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtMRN.setEditable(false);
        txtMRN.setForeground(new java.awt.Color(51, 51, 51));
        txtMRN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtMRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMRNActionPerformed(evt);
            }
        });

        lblState35.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState35.setForeground(new java.awt.Color(102, 102, 102));
        lblState35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState35.setText("Allergy 3");
        lblState35.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txta3.setEditable(false);
        txta3.setForeground(new java.awt.Color(51, 51, 51));
        txta3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txta3ActionPerformed(evt);
            }
        });

        lblState36.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState36.setForeground(new java.awt.Color(102, 102, 102));
        lblState36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState36.setText("Allergy 2");
        lblState36.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblState9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState9.setForeground(new java.awt.Color(102, 102, 102));
        lblState9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState9.setText("Bank Name");
        lblState9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtBNC.setEditable(false);
        txtBNC.setForeground(new java.awt.Color(51, 51, 51));
        txtBNC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtBNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBNCActionPerformed(evt);
            }
        });

        lblState13.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState13.setForeground(new java.awt.Color(102, 102, 102));
        lblState13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState13.setText("Bank Account Number");
        lblState13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtRNC.setEditable(false);
        txtRNC.setForeground(new java.awt.Color(51, 51, 51));
        txtRNC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtRNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRNCActionPerformed(evt);
            }
        });

        lblState14.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState14.setForeground(new java.awt.Color(102, 102, 102));
        lblState14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState14.setText("Routing Number");
        lblState14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtABC.setEditable(false);
        txtABC.setForeground(new java.awt.Color(51, 51, 51));
        txtABC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtABC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtABCActionPerformed(evt);
            }
        });

        lblState15.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState15.setForeground(new java.awt.Color(102, 102, 102));
        lblState15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState15.setText("Account Balance");
        lblState15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtAccountType.setEditable(false);
        txtAccountType.setForeground(new java.awt.Color(51, 51, 51));
        txtAccountType.setText("Checking");
        txtAccountType.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountTypeActionPerformed(evt);
            }
        });

        lblState16.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState16.setForeground(new java.awt.Color(102, 102, 102));
        lblState16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState16.setText("Account Type");
        lblState16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtBANC.setEditable(false);
        txtBANC.setForeground(new java.awt.Color(51, 51, 51));
        txtBANC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtBANC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBANCActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 188, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Address");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 181, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Saving Account Details");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 181, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Checking Account Details");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 181, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("License Information ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 181, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Medical Information ");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 188, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Demographic Information");

        lblState17.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lblState17.setForeground(new java.awt.Color(102, 102, 102));
        lblState17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState17.setText("DOB");
        lblState17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtDateOfBirth.setEditable(false);
        txtDateOfBirth.setForeground(new java.awt.Color(51, 51, 51));
        txtDateOfBirth.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        txtDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfBirthActionPerformed(evt);
            }
        });

        lblReportImage.setForeground(new java.awt.Color(153, 153, 153));
        lblReportImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportImage.setText("photo");
        lblReportImage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtBANS)
                                    .addComponent(lblState8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBNS)
                                    .addComponent(lblState7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblState12, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtRNS))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblState11, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtABS))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblState10, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtBankName11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFirstName)
                                    .addComponent(lblState1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblState2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblState17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblState3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblState4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblState5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSSN)
                                    .addComponent(lblState6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtLN, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(lblState26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblState25, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(txtDoi))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblState30, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                            .addComponent(txtDoe))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblState29, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtStreet)
                                            .addComponent(lblState20, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCity)
                                            .addComponent(lblState19, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtState)
                                            .addComponent(lblState24, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtZipcode)
                                            .addComponent(lblState23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(60, 60, 60)
                                .addComponent(lblReportImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblState13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblState9, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRNC)
                                    .addComponent(lblState14, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtABC)
                                    .addComponent(lblState15, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblState16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(316, 316, 316))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblState32, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtMRN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblState31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txta1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblState36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txta2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblState35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txta3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBANC, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBNC, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(694, 694, 694))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblState2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(txtLastName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblState4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblState17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblState3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblState5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblState6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                .addComponent(txtHeight)
                                .addComponent(txtDateOfBirth)
                                .addComponent(txtWeight)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblState29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblState30, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDoe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblState26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(lblState25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLN, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                    .addComponent(txtDoi))))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblState23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblState19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblState24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblState20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtZipcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblReportImage, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblState8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBANS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblState7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBNS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtBankName11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblState12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRNS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtABS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblState11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblState14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRNC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblState13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblState9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBANC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtABC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBNC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblState32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblState31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txta1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblState35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txta3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblState36, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txta2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtRNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRNSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRNSActionPerformed

    private void txtBNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBNSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBNSActionPerformed

    private void txtBANSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBANSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBANSActionPerformed

    private void txtBankName11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankName11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankName11ActionPerformed

    private void txtABSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtABSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtABSActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetActionPerformed

    private void txtZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipcodeActionPerformed

    private void txtDoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoeActionPerformed

    private void txtDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoiActionPerformed

    private void txtLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNActionPerformed

    private void txtBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBtActionPerformed

    private void txta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txta2ActionPerformed

    private void txta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txta1ActionPerformed

    private void txtMRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMRNActionPerformed

    private void txta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txta3ActionPerformed

    private void txtBNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBNCActionPerformed

    private void txtRNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRNCActionPerformed

    private void txtABCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtABCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtABCActionPerformed

    private void txtAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountTypeActionPerformed

    private void txtBANCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBANCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBANCActionPerformed

    private void txtDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfBirthActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblReportImage;
    private javax.swing.JLabel lblState1;
    private javax.swing.JLabel lblState10;
    private javax.swing.JLabel lblState11;
    private javax.swing.JLabel lblState12;
    private javax.swing.JLabel lblState13;
    private javax.swing.JLabel lblState14;
    private javax.swing.JLabel lblState15;
    private javax.swing.JLabel lblState16;
    private javax.swing.JLabel lblState17;
    private javax.swing.JLabel lblState19;
    private javax.swing.JLabel lblState2;
    private javax.swing.JLabel lblState20;
    private javax.swing.JLabel lblState23;
    private javax.swing.JLabel lblState24;
    private javax.swing.JLabel lblState25;
    private javax.swing.JLabel lblState26;
    private javax.swing.JLabel lblState29;
    private javax.swing.JLabel lblState3;
    private javax.swing.JLabel lblState30;
    private javax.swing.JLabel lblState31;
    private javax.swing.JLabel lblState32;
    private javax.swing.JLabel lblState35;
    private javax.swing.JLabel lblState36;
    private javax.swing.JLabel lblState4;
    private javax.swing.JLabel lblState5;
    private javax.swing.JLabel lblState6;
    private javax.swing.JLabel lblState7;
    private javax.swing.JLabel lblState8;
    private javax.swing.JLabel lblState9;
    private javax.swing.JTextField txtABC;
    private javax.swing.JTextField txtABS;
    private javax.swing.JTextField txtAccountType;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBANC;
    private javax.swing.JTextField txtBANS;
    private javax.swing.JTextField txtBNC;
    private javax.swing.JTextField txtBNS;
    private javax.swing.JTextField txtBankName11;
    private javax.swing.JTextField txtBt;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtDoe;
    private javax.swing.JTextField txtDoi;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLN;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtRNC;
    private javax.swing.JTextField txtRNS;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipcode;
    private javax.swing.JTextField txta1;
    private javax.swing.JTextField txta2;
    private javax.swing.JTextField txta3;
    // End of variables declaration//GEN-END:variables

private void displayReport(){

    
    txtBANS.setText(savingAccount.getAccountNumber());
    txtRNS.setText(savingAccount.getBankRoutinNumber());
    txtBNS.setText(savingAccount.getBankName());
    txtABS.setText(savingAccount.getAccountBalance());
    
    txtBANC.setText(checkingAccount.getBankRoutinNumber());
    txtRNC.setText(checkingAccount.getBankRoutinNumber());
    txtBNC.setText(checkingAccount.getBankName());
    txtABC.setText(checkingAccount.getAccountBalance());
    
     txtFirstName.setText(demographicInformation.getFirstName());
    txtLastName.setText(demographicInformation.getLastName());
    txtDateOfBirth.setText(demographicInformation.getDateOfBirth());
    txtAge.setText(demographicInformation.getAge());
    txtHeight.setText(demographicInformation.getHeight());
    txtWeight.setText(demographicInformation.getWeight());
    txtSSN.setText(demographicInformation.getSocialSecurityNumber());
    
    txtStreet.setText(adress.getStreet());
    txtCity.setText(adress.getCity());
    txtState.setText(adress.getState());
    txtZipcode.setText(adress.getZipcode());
    
    txtLN.setText(license.getLicenseNumber());
    txtDoi.setText(license.getIssuedDate());
    txtDoe.setText(license.getDateOfExpiration());
    txtBt.setText(license.getBloodType());
    
    txtMRN.setText(medicalInfo.getMedicalRecordNumber());
    txta1.setText(medicalInfo.getAllergy1());
    txta2.setText(medicalInfo.getAllergy2());
    txta3.setText(medicalInfo.getAllergy3());
    
   lblReportImage.setIcon(license.imageIcon);
    
    
    
    
} 
}
